// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto
package sources;

public final class TradeOuterClass {
  private TradeOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TradeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Trade)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 trade_id = 1;</code>
     */
    long getTradeId();

    /**
     * <code>double price = 2;</code>
     */
    double getPrice();

    /**
     * <code>double qty = 3;</code>
     */
    double getQty();

    /**
     * <code>double event_time = 4;</code>
     */
    double getEventTime();

    /**
     * <code>double ingestion_time = 5;</code>
     */
    double getIngestionTime();
  }
  /**
   * Protobuf type {@code Trade}
   */
  public  static final class Trade extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Trade)
      TradeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Trade.newBuilder() to construct.
    private Trade(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Trade() {
      tradeId_ = 0L;
      price_ = 0D;
      qty_ = 0D;
      eventTime_ = 0D;
      ingestionTime_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Trade(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              tradeId_ = input.readInt64();
              break;
            }
            case 17: {

              price_ = input.readDouble();
              break;
            }
            case 25: {

              qty_ = input.readDouble();
              break;
            }
            case 33: {

              eventTime_ = input.readDouble();
              break;
            }
            case 41: {

              ingestionTime_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TradeOuterClass.internal_static_Trade_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TradeOuterClass.internal_static_Trade_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TradeOuterClass.Trade.class, TradeOuterClass.Trade.Builder.class);
    }

    public static final int TRADE_ID_FIELD_NUMBER = 1;
    private long tradeId_;
    /**
     * <code>int64 trade_id = 1;</code>
     */
    public long getTradeId() {
      return tradeId_;
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private double price_;
    /**
     * <code>double price = 2;</code>
     */
    public double getPrice() {
      return price_;
    }

    public static final int QTY_FIELD_NUMBER = 3;
    private double qty_;
    /**
     * <code>double qty = 3;</code>
     */
    public double getQty() {
      return qty_;
    }

    public static final int EVENT_TIME_FIELD_NUMBER = 4;
    private double eventTime_;
    /**
     * <code>double event_time = 4;</code>
     */
    public double getEventTime() {
      return eventTime_;
    }

    public static final int INGESTION_TIME_FIELD_NUMBER = 5;
    private double ingestionTime_;
    /**
     * <code>double ingestion_time = 5;</code>
     */
    public double getIngestionTime() {
      return ingestionTime_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (tradeId_ != 0L) {
        output.writeInt64(1, tradeId_);
      }
      if (price_ != 0D) {
        output.writeDouble(2, price_);
      }
      if (qty_ != 0D) {
        output.writeDouble(3, qty_);
      }
      if (eventTime_ != 0D) {
        output.writeDouble(4, eventTime_);
      }
      if (ingestionTime_ != 0D) {
        output.writeDouble(5, ingestionTime_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (tradeId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, tradeId_);
      }
      if (price_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, price_);
      }
      if (qty_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, qty_);
      }
      if (eventTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, eventTime_);
      }
      if (ingestionTime_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, ingestionTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TradeOuterClass.Trade)) {
        return super.equals(obj);
      }
      TradeOuterClass.Trade other = (TradeOuterClass.Trade) obj;

      boolean result = true;
      result = result && (getTradeId()
          == other.getTradeId());
      result = result && (
          java.lang.Double.doubleToLongBits(getPrice())
          == java.lang.Double.doubleToLongBits(
              other.getPrice()));
      result = result && (
          java.lang.Double.doubleToLongBits(getQty())
          == java.lang.Double.doubleToLongBits(
              other.getQty()));
      result = result && (
          java.lang.Double.doubleToLongBits(getEventTime())
          == java.lang.Double.doubleToLongBits(
              other.getEventTime()));
      result = result && (
          java.lang.Double.doubleToLongBits(getIngestionTime())
          == java.lang.Double.doubleToLongBits(
              other.getIngestionTime()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TRADE_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTradeId());
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPrice()));
      hash = (37 * hash) + QTY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getQty()));
      hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getEventTime()));
      hash = (37 * hash) + INGESTION_TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getIngestionTime()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TradeOuterClass.Trade parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TradeOuterClass.Trade parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TradeOuterClass.Trade parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TradeOuterClass.Trade parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TradeOuterClass.Trade parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TradeOuterClass.Trade parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TradeOuterClass.Trade parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TradeOuterClass.Trade parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TradeOuterClass.Trade parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TradeOuterClass.Trade parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TradeOuterClass.Trade parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TradeOuterClass.Trade parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    // @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TradeOuterClass.Trade prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    // @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Trade}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Trade)
        TradeOuterClass.TradeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TradeOuterClass.internal_static_Trade_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TradeOuterClass.internal_static_Trade_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TradeOuterClass.Trade.class, TradeOuterClass.Trade.Builder.class);
      }

      // Construct using TradeOuterClass.Trade.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tradeId_ = 0L;

        price_ = 0D;

        qty_ = 0D;

        eventTime_ = 0D;

        ingestionTime_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TradeOuterClass.internal_static_Trade_descriptor;
      }

      // @java.lang.Override
      public TradeOuterClass.Trade getDefaultInstanceForType() {
        return TradeOuterClass.Trade.getDefaultInstance();
      }

      // @java.lang.Override
      public TradeOuterClass.Trade build() {
        TradeOuterClass.Trade result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      // @java.lang.Override
      public TradeOuterClass.Trade buildPartial() {
        TradeOuterClass.Trade result = new TradeOuterClass.Trade(this);
        result.tradeId_ = tradeId_;
        result.price_ = price_;
        result.qty_ = qty_;
        result.eventTime_ = eventTime_;
        result.ingestionTime_ = ingestionTime_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TradeOuterClass.Trade) {
          return mergeFrom((TradeOuterClass.Trade)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TradeOuterClass.Trade other) {
        if (other == TradeOuterClass.Trade.getDefaultInstance()) return this;
        if (other.getTradeId() != 0L) {
          setTradeId(other.getTradeId());
        }
        if (other.getPrice() != 0D) {
          setPrice(other.getPrice());
        }
        if (other.getQty() != 0D) {
          setQty(other.getQty());
        }
        if (other.getEventTime() != 0D) {
          setEventTime(other.getEventTime());
        }
        if (other.getIngestionTime() != 0D) {
          setIngestionTime(other.getIngestionTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TradeOuterClass.Trade parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TradeOuterClass.Trade) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long tradeId_ ;
      /**
       * <code>int64 trade_id = 1;</code>
       */
      public long getTradeId() {
        return tradeId_;
      }
      /**
       * <code>int64 trade_id = 1;</code>
       */
      public Builder setTradeId(long value) {
        
        tradeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 trade_id = 1;</code>
       */
      public Builder clearTradeId() {
        
        tradeId_ = 0L;
        onChanged();
        return this;
      }

      private double price_ ;
      /**
       * <code>double price = 2;</code>
       */
      public double getPrice() {
        return price_;
      }
      /**
       * <code>double price = 2;</code>
       */
      public Builder setPrice(double value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price = 2;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0D;
        onChanged();
        return this;
      }

      private double qty_ ;
      /**
       * <code>double qty = 3;</code>
       */
      public double getQty() {
        return qty_;
      }
      /**
       * <code>double qty = 3;</code>
       */
      public Builder setQty(double value) {
        
        qty_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double qty = 3;</code>
       */
      public Builder clearQty() {
        
        qty_ = 0D;
        onChanged();
        return this;
      }

      private double eventTime_ ;
      /**
       * <code>double event_time = 4;</code>
       */
      public double getEventTime() {
        return eventTime_;
      }
      /**
       * <code>double event_time = 4;</code>
       */
      public Builder setEventTime(double value) {
        
        eventTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double event_time = 4;</code>
       */
      public Builder clearEventTime() {
        
        eventTime_ = 0D;
        onChanged();
        return this;
      }

      private double ingestionTime_ ;
      /**
       * <code>double ingestion_time = 5;</code>
       */
      public double getIngestionTime() {
        return ingestionTime_;
      }
      /**
       * <code>double ingestion_time = 5;</code>
       */
      public Builder setIngestionTime(double value) {
        
        ingestionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double ingestion_time = 5;</code>
       */
      public Builder clearIngestionTime() {
        
        ingestionTime_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Trade)
    }

    // @@protoc_insertion_point(class_scope:Trade)
    private static final TradeOuterClass.Trade DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TradeOuterClass.Trade();
    }

    public static TradeOuterClass.Trade getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Trade>
        PARSER = new com.google.protobuf.AbstractParser<Trade>() {
      // @java.lang.Override
      public Trade parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Trade(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Trade> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Trade> getParserForType() {
      return PARSER;
    }

    // @java.lang.Override
    public TradeOuterClass.Trade getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Trade_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Trade_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013trade.proto\"a\n\005Trade\022\020\n\010trade_id\030\001 \001(\003" +
      "\022\r\n\005price\030\002 \001(\001\022\013\n\003qty\030\003 \001(\001\022\022\n\nevent_ti" +
      "me\030\004 \001(\001\022\026\n\016ingestion_time\030\005 \001(\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Trade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Trade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Trade_descriptor,
        new java.lang.String[] { "TradeId", "Price", "Qty", "EventTime", "IngestionTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
